### ISSUE TITLE
Error after npm run dev

### ISSUE THREAD

**Issue by cve** [egoist/eva-webpack-simple#1]
Hi,

I'm trying to install and run and this the result:
![screen](https://cloud.githubusercontent.com/assets/594384/18671804/cdaf45cc-7f45-11e6-8870-959f7316429e.png)

**Comment by egoist** [comment]
I'm sorry for this, [webpack's latest release](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23) has breaking changes but didn't follow the semantic versioning, so it failed.

I have fixed webpack's version to `2.1.0-beta22`, reinstall vbuild would fix the issue.

**Comment by cve** [comment]
Now it works, thank you so much.
