### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by zigomir** [egoist/eva-webpack-simple#2]
Nice template you have here!

I was trying it out and found issues running `npm run dev`. It only worked when I added `vue-loader` and `vue-template-compiler`. (`npm install vue-template-compiler --save` && `npm install vue-loader --save`) Was something changed in `vbuild`?

**Comment by egoist** [comment]
Yep, since `vue` and `vue-template-compiler` version always mismatches so I exclude them from vbuild and let user handle it.
